#!/bin/sh
#
# Back up all local branches (`refs/heads/*`) to a bundle.  Only the commits
# since the branch-point are added, so the packs should be minimal in size.
#

set -e

if [ "$1" ]
then
  path="$1"
else
  state_path=$HOME/.local/state/git-backup
  mkdir -p $state_path
  hostname=`hostname --fqdn`
  escaped_pwd=`pwd | sed -e s,/,_,g`
  time=`date +%Y%m%d%H%M%S`
  path="$state_path/${hostname}${escaped_pwd}_${time}.pack"
fi

specs=`git for-each-ref 'refs/heads/*' --format 'origin..%(refname)'`
count=`echo "$specs" | wc -l`

log() {
  echo >&2 "\033[38;2;67;230;96m""✇ git-backup: $*""\033[0m"
}

has_commits() {
  for spec in $specs
  do
    if [ "`git log $spec`" ]
    then
      return
    fi
  done
  return 1
}

if [ -z "$specs" ]
then
  log "no branches"
  exit 0
fi

if ! has_commits
then
  log "no local commits"
  exit 0
fi

git bundle create $path $specs
log "backed up $count branch(es) to ... $path"
