repos:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-check
        files: &python_files '(Î¼\.|u\.|\.py)$'
        types_or: [python, file]
        args: [--fix]
      - id: ruff-format
        files: *python_files
        types_or: [python, file]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'
    hooks:
      - id: mypy
        args:
          - --ignore-missing
        additional_dependencies:
          - types-Markdown
          - types-tabulate
