#!/bin/bash

cd "$(dirname "$0")"
set -ex


# tmux
cp tmux.conf ~/.tmux.conf


# vim
cp vimrc ~/.vimrc
mkdir -p ~/.vim/autoload/
cp vim/autoload/* ~/.vim/autoload
tar -C ~/.vim/ -xf vim/plugged.tar.xz


# bash
if [ -f ~/.bashrc ] && [ ! -f ~/.config/bash/original.sh ]
then
  mkdir -p ~/.config/bash/
  mv ~/.bashrc ~/.config/bash/original.sh
fi
cp bashrc ~/.bashrc
