#!/bin/bash

announce() {
  echo "  + $1"
}

block_in_file() {
  local path="$1"
  local comment_character="$2"
  local position="$3"

  local begin_marker="$comment_character -----BEGIN MICRODOT-----"
  local end_marker="$comment_character -----END MICRODOT-----"

  local time=$(date +%s)
  local old_path="$path.old.$time"
  local new_path="$path.new.$time"

  announce "$path"

  {
    if [ -e "$path" ]
    then
      local before="$(grep -B999 "^$begin_marker" $path)"
      local after="$(grep -A999 "^$end_marker" $path)"
      if [ "$before" ] && [ "$after" ]
      then
        echo "$before"
        cat
        echo "$after"
      else
        if [ $position = 'beginning' ]
        then
          echo "$begin_marker"
          cat
          echo "$end_marker"
          echo
          cat "$path"
        else
          cat "$path"
          echo
          echo "$begin_marker"
          cat
          echo "$end_marker"
        fi
      fi
    else
      echo "$begin_marker"
      cat
      echo "$end_marker"
    fi
  } > $new_path

  if [ -e "$path" ]
  then
    mv $path $old_path
  fi

  mv $new_path $path
}


cd "$(dirname "$0")"
set -e


# tmux
block_in_file ~/.tmux.conf \# beginning <<...
source $PWD/tmux/tmux.conf
...


# vim
block_in_file ~/.vimrc \" beginning <<...
source $PWD/vim/vimrc
...
mkdir -p ~/.vim/autoload/
cp vim/autoload/* ~/.vim/autoload
tar -C ~/.vim/ -xf vim/plugged.tar.gz


# bash
block_in_file ~/.bashrc \# beginning <<...
source $PWD/bash/bashrc
...


# git
mkdir -p ~/.config/git
block_in_file ~/.gitconfig \# beginning <<...
[include]
path = $PWD/git/config

[core]
excludesfile = $PWD/git/ignore
...


# ssh
mkdir -p -m 0700 ~/.ssh/
block_in_file ~/.ssh/config \# end <<...
Host *
Include $PWD/ssh/config
...


# fish
fish="$HOME/.config/fish/conf.d"
announce $fish
cp -n fish/*.fish $fish
