#!/bin/bash

cd "$(dirname "$0")"
set -ex


# tmux
cp tmux.conf ~/.tmux.conf


# vim
cp vimrc ~/.vimrc
mkdir -p ~/.vim/autoload/
cp vim/autoload/* ~/.vim/autoload
tar -C ~/.vim/ -xf vim/plugged.tar.xz


# bash
if [ -f ~/.bashrc ] && [ ! -f ~/.config/bash/original.sh ]
then
  mkdir -p ~/.config/bash/
  mv ~/.bashrc ~/.config/bash/original.sh
fi
cp bashrc ~/.bashrc


# git
mkdir -p ~/.config/git
cp git/config ~/.config/git/config
cp git/ignore ~/.config/git/ignore

if [ -f ~/.gitconfig ]
then
  mv ~/.gitconfig ~/.config/git/config.local
fi

if [ -f ~/.gitignore ]
then
  mv ~/.gitignore ~/.config/git/ignore.local
fi
