# If we are not running interactively, don't do anything.
[ -z "$PS1" ] && return

# A way to disable the startup logic, if something goes horribly wrong.
[ "$MICRODOT_DISABLED" ] && return

# Include the common environment settings shared with ~/.profile
source $MICRODOT_INSTALL_PATH/sh/profile

# Restart inside tmux
if [ "$SSH_TTY" ] && [ -z "$TMUX" ]
then
  # Force 256 colour UTF-8 output
  # Start (or attach to) a session called `main`
  exec tmux -2u new-session -A -D -s main
fi

# Restart inside fish
fish=$(command -v fish)
if [ $fish ]
then
  export SHELL=$fish
  exec $fish -i
fi
