#!/bin/sh

set -ex

export PATH="\
$HOME/bin:\
$HOME/.local/bin:\
/usr/local/sbin:\
/usr/sbin:\
/sbin:\
/usr/local/bin:\
/usr/bin:\
/bin:\
"

base="`dirname "$0"`"

xsetroot -solid black

xrdb -merge $base/Xresources
if [ -f ~/.Xresources ]
then
  xrdb -merge ~/.Xresources
fi

gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

if command -v pulseaudio
then
  pulseaudio --start
fi

x-terminal-emulator &

# Make ~/.XCompose work
xmodmap -e 'keysym Alt_L = Multi_key'

# Required to get firefox to respect ~/.XCompose
export GTK_IM_MODULE='xim'

export TZ="Europe/London"
export LC_TIME="en_GB.UTF-8"
export LC_PAPER="en_GB.UTF-8"

# Force a dark theme
export GTK_THEME="Adwaita:dark"
export GTK2_RC_FILES="/usr/share/themes/Adwaita-dark/gtk-2.0/gtkrc"
export QT_STYLE_OVERRIDE="adwaita-dark"

if command -v ssh-agent
then
  exec ssh-agent i3
else
  exec i3
fi
