#!/bin/bash

set -ex

source ~/.bash_profile

xsetroot -solid black

xrdb -merge $MICRODOT_INSTALL_PATH/X11/Xresources

if [ -f ~/.Xresources ]
then
  xrdb -merge ~/.Xresources
fi

if command -v gsettings
then
  gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
fi

if command -v pulseaudio
then
  pulseaudio --start
fi

x-terminal-emulator &

# Make ~/.XCompose work
xmodmap -e 'keysym Alt_L = Multi_key'

# Required to get firefox to respect ~/.XCompose
export GTK_IM_MODULE='xim'

# Force a dark theme
export GTK_THEME="Adwaita:dark"
export GTK2_RC_FILES="/usr/share/themes/Adwaita-dark/gtk-2.0/gtkrc"
export QT_STYLE_OVERRIDE="adwaita-dark"

if command -v ssh-agent
then
  exec ssh-agent i3
else
  exec i3
fi
