#!/bin/sh

export PATH="\
$HOME/bin:\
$HOME/.local/bin:\
/usr/local/sbin:\
/usr/sbin:\
/sbin:\
/usr/local/bin:\
/usr/bin:\
/bin:\
"

base="`dirname "$0"`"

xsetroot -solid black

xrdb -merge $base/Xresources

gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

if command -v pulseaudio
then
  pulseaudio --start
fi

x-terminal-emulator &

# Required to get firefox to respect ~/.XCompose
export GTK_IM_MODULE='xim'

export TZ="Europe/London"
export LC_TIME="en_GB.UTF-8"
export LC_PAPER="en_GB.UTF-8"

exec $HOME/.local/bin/i3
