#!/bin/sh

time=`TZ=C date --iso=seconds`
log=`mktemp /tmp/greetd-init.$USER.$time.XXXXXXXX.log`
exec >>$log 2>&1

set -ex

. ~/.profile

if command -v niri
then
  exec niri --session
fi

echo >&2 "No window managers installed!"
exit 3
