#!/bin/bash

pane_current_path="$1"

blue="#[fg=#28a7a7]"

dir="$(basename "$pane_current_path")"
branch=$(cd "$pane_current_path" && git rev-parse --abbrev-ref HEAD)

if [ "$branch" ]
then
  echo "${blue}${dir}  ⎇ ${branch}"
else
  echo "${blue}${dir}"
fi
