# vim: ft=sh

# Useful for helping other tools' config files to find sibling files.
export MICRODOT_INSTALL_PATH="$(dirname $(dirname $BASH_SOURCE))"

# Generic config
export EDITOR='vim'
export LANG='en_US.UTF-8'
export LC_PAPER="en_GB.UTF-8"
export LC_TIME='en_GB.UTF-8'
export TZ='Europe/London'

# apt tweaks
export APT_CONFIG="$HOME/.config/apt.conf"

# Set up PATH
for p in              \
  ~/bin               \
  ~/.local/bin        \
  ~/.cargo/bin        \
  /usr/local/sbin     \
  /usr/sbin           \
  /sbin
do
  [ -d $path ] && export PATH="$p:$PATH"
done

source ~/.bashrc
