# If we are not running interactively, don't do anything.
[ -z "$PS1" ] && return

# Some basic environment stuff that we'll need everywhere, in particular tmux,
# which launches before fish.
export EDITOR='vim'
export LANG='en_US.UTF-8'
export LC_TIME='en_GB.UTF-8'
export TZ='Europe/London'

# apt tweaks
export APT_CONFIG="$HOME/.config/apt.conf"

# A way to disable the startup logic, if something goes horribly wrong.
[ "$MICRODOT_DISABLED" ] && return

# Fish and Tmux might be on a weird path, so we have to set that up now.
[ -d /opt/homebrew/bin ] && PATH="/opt/homebrew/bin:$PATH"
[ -d $HOME/.local/bin ] && PATH="$HOME/.local/bin:$PATH"

# Restart inside tmux
if [ "$SSH_TTY" ] || [ "$LETS_GET" = "CREATIVE" ] && [ -z "$TMUX" ]
then
  TZ=Europe/London tmux -u -2 new-session -A -D -s main && exit
  return
fi

# Restart inside fish
if [ "$SHELL" != "fish" ]
then
  env SHELL=fish fish -i && exit
  return
fi
