#!/bin/sh

fuzzel_wmenu() {
  # Fuzzel in wmenu-pretend mode
  fuzzel \
    --dmenu \
    \
    --font 'IosevkaTerm:size=14:style=Extended' \
    --prompt '' \
    \
    --anchor top \
    --y-margin 40 \
    --width 50 \
    --horizontal-pad 16 \
    --lines 10 \
    \
    --border-radius 20 \
    --border-width 0 \
    \
    --background 000000E0 \
    --text-color BBBBBBFF \
    --prompt-color EEEEEEFF \
    --selection-color 005577FF \
    --selection-text-color EEEEEEFF \
    --match-color EEEEEEFF \
    --selection-match-color EEEEEEFF \
    \
    ;
}

ask_for_command() {
  dmenu_path | fuzzel_wmenu
}

response=`ask_for_command`

if [ "$response" ]
then
  exec $response
fi
